import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class CheckScreen extends StatefulWidget {
  const CheckScreen({Key? key}) : super(key: key);

  @override
  _CheckScreenState createState() => _CheckScreenState();
}

class _CheckScreenState extends State<CheckScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Search For Services"),
        actions: [
          IconButton(
              icon: Icon(Icons.search),
              onPressed: () {
                showSearch(context: context, delegate: CustomSearchDelegate());
              }),
        ],
      ),
    );
  }
}

class CustomSearchDelegate extends SearchDelegate {
  final searchTerms = [
    "ETA certificate",
    "ETA certification",
    "ETA approval",
    "Recycler",
    "scrapper",
    "dispose off",
    "waste management services",
    "LMPC certificate",
    "LMPC certificate for import",
    "LMPC certificate online",
    "LMPC certification",
    "Bio-medical waste management",
    "STQC certification",
    "STQC certificate",
    "CPCB guidelines for poultry farms",
    "CPCB guidelines for environmental management of dairy farms and gaushalas",
    "Delhi Pollution Control Committee (DPCC) & Waste Management Authorization",
    "Haryana State Pollution Control Board, HPCB",
    "Uttar Pradesh Pollution Control Board, UPPCB",
    "Maharashtra State Pollution Control Board, MPCB",
    "Delhi Forest Department",
    "LMPC certificate",
    "LMPC certificate for imports",
    "LMPC certificate online",
    "LMPC certification",
    "Bihar State Pollution Control Board, BPCB",
    "Gujarat State Pollution Control Board, GPCB",
    "Maharashtra State Pollution Control Board, MPCBM",
    "Public limited company",
    "public limited incorporation",
    "incorporation of public limited company",
    "formation of public limited company",
    "public limited company formation",
    "Delhi Pollution Control Committee, DPCC",
    "DPCC registration",
    "CPCB DPCC",
    "DPCC approval",
    "CRA type approval",
    "Qatar type approval",
    "CRA Qatar type approval",
    " communications regulatory authority",
    "cra qatar",
    "NTC type approval",
    "NTC philippines type approval",
    "Philippines type approval / NTC Thailand type approval",
    "Thailand type approval",
    "Philippines radio type approval",
    "NTC approval",
    "NTC Philippines",
    "NTC list",
    "MTC type approval",
    "MTC Peru type approval",
    "Peru type approval",
    "Peru MTC telecom approval",
    "MTC certification",
    "TRA type approval",
    "TRA Oman type approval",
    "Oman type approval / TRA type approval",
    "TRA UAE type approval",
    "UAE type approval",
    "oman radio type approval",
    "TRA certification",
    "TRa registration",
    "ANRT type approval",
    "ANRT Morocco type approval",
    "Morocco type approval",
    "ANRT certification",
    "morocco anrt type",
    "TRA type approval",
    "TRA Lebanon type approval",
    "type approval",
    "TRA certificate",
    "TRA regulations",
    "CITRA type approval",
    "CITRA Kuwait type approval",
    "Kuwait type approval",
    "Kuwait CITRA",
    "CITRA Kuwait",
    "CITRA regulations",
    "TRC Cambodia type approval",
    "Cambodia type approval",
    "TRC certification",
    "DSRT type approval",
    "Macau type approval",
    "DSRT Macau type approval",
    "Sirim type approval",
    "Malaysia type approval",
    "Sirim Malaysia type approval",
    "SIRIM certification",
    "SIRIM malaysia",
    "SIRIM QAS",
    "NTA type approval",
    "Nepal NTA type approval",
    "NTA type approval",
    "NTA Nepal type approval",
    "NTA imei",
    "NTA registration",
    "PTA type approval",
    "Pakistan PTA type approval",
    "PTA Pakistan type approval",
    "PTA mobile registration",
    "IMDA equipment registration",
    "Singapore IMDA equipment registration",
    "IMDA singapore equipment registration",
    "IMDA Telecom Approval",
    "imda telecommunication equipment",
    "IMDA certification",
    "IMDA standards",
    "TCRA type approval",
    "Tanzania TCRA type approval",
    "Tanzania type approval",
    "TCRA Tanzania type approval",
    "TCRA Tanzania",
    "CONATEL type approval",
    "CONATEL approval",
    "CONATEL Venezuela type approval",
    "Venezuela CONATEL approval",
    "ICT type approval certificate (TAC)",
    "Declaration of Conformity (DoC)",
    "VNTA type approval",
    "Vietnam type approval",
    "ICT Vietnam type approval",
    "VNTA Vietnam type approval",
    "ICT approval",
    "ICT Qatar",
    "MITIT approval",
    "MITIT Yemen type approval",
    "MITIT approval",
    "Yemen MITIT type approval",
    "Barbados Type Approval For Telecom and Radio Equipment",
    "Barbados type approval",
    "Barbados global approvals",
    "Barbados certification",
    "NOC Bangladesh ",
    "Bangladesh NOC",
    "Bangladesh certification",
    "Bangladesh global approval",
    "AITI type approval",
    "Brunei AITI approval",
    "Brunei approval",
    "Brunei global approval",
    "Brunei certification",
    "AITI approval",
    "CRS Homologation",
    "Colombia CRS homologation",
    "Colombia homologation",
    "Colombia global approval",
    "Colombia certification",
    "SUTEL Approval",
    "Costa Rica SUTEL Approval",
    "Costa Rica approval",
    "Costa Rica global approval",
    "Costa Rica certification",
    "SUTEL certification",
    "Costa Rica type approval",
    "INDOTEL Type Approval",
    "Dominican Republic INDOTEL Type Approval",
    "Dominican Republic approval",
    "Dominican Republic global approval",
    "Dominican Republic certification",
    "Dominican Republic Type Approval",
    "ARCOTEL Type Approval",
    "Ecuador ARCOTEL Type Approval",
    "Ecuador type approval",
    "Ecuador global approval",
    "Ecuador certification",
    "ARCOTEL approval",
    "HKCA Telecom Equipment Certification",
    "HKCA certification",
    "HKCA registration",
    "HKCA Hong Kong certification",
    "Hong Kong HKCA certification",
    "Hong Kong certification",
    "Hong Kong approval",
    "NTRA Type Approval",
    "Egypt NTRA  Type Approval",
    "Egypt NTRA Approval",
    "NTRA Egypt approval",
    "NTRA Approval",
    "Egypt global approval",
    "Egypt certification",
    "Egypt radio type approval",
    "NTRA egypt, NTRA certification",
    "SDPPI Type Approval",
    "Indonesia SDPPI Type Approval",
    "Indonesia SDPPI Approval",
    "SDPPI Indonesia approval",
    "SDPPI Approval",
    "Indonesia global approval",
    "Indonesia certification",
    "SDPPI certification",
    "Indonesian standards",
    "ISRAEL Global Certification",
    "MoC approval",
    "MoC type approval",
    "MoE type approval",
    "MoE approval",
    "SII type approval",
    "SII approval",
    "Israel global certification",
    "Israel certification",
    "MoC certification",
    "Israel MoC",
    "TRC type approval",
    "TRC Jordan type approval",
    "Jordan type approval / TRC type approval",
    "TRC Sri Lanka type approval",
    "Sri Lanka type approval",
    "Jordan TRC type approval",
    "TRC approval",
    "Telepermit Certificate",
    "New Zealand telepermit certificate",
    "New Zealand certification",
    "New Zealand global approval",
    "TRA approval",
    "Bahrain TRA approval",
    "Bahrain approval",
    "Bahrain global approval",
    "Bahrain certification",
    "Oman radio type approval",
    "UAE TRA",
    "Bahrain radio type approval",
    "Ministere des Technologies de la Communication",
    "Tunisia Type Approval",
    "Tunisia global approval",
    "Tunisia certification",
    "CITC Type Approval",
    "Saudi Arabia CITC Type Approval",
    "Saudi Arabia CITC Approval",
    "CITC Saudi Arabia approval",
    "CITC Approval",
    "Saudi Arabia certification",
    "Saudi Arabia global approval",
    "Saudi Arabia Radio type Approval",
    "CITC Certification, CITC Saudi",
    'SUBTEL approval',
    "Chile SUBTEL approval",
    "Chile approval",
    "Chile global approval",
    "Chile certification",
    "chile radio type approval",
    "SUBTEL approval chile",
    "SUBTEL certification",
    "Punjab Pollution Control Board NOC, PPCB",
    "Karnataka Pollution Control Board NOC, KSPCB",
    "Madhya Pradesh Pollution Board NOC, MPPCB",
    "Rajasthan Pollution Board NOC, RPCB",
    "Tamil Nadu Pollution Board NOC, TNPCB",
    "Telangana Pollution Board NOC, TSPCB",
    "Chhattisgarh Pollution Board NOC, CPCB",
    "Jharkhand Pollution Board NOC, JSPCB",
    "Uttarakhand Environment Protection and Pollution Board NOC, UEPPCB",
    "Himachal Pradesh Pollution Board NOC, HPPCB",
    "West Bengal Pollution Board NOC, WBPCB",
    "Kerala Pollution Board NOC, KPCB",
    "Odisha Pollution Board NOC, OSPCB",
    "Puducherry Pollution Control Committee NOC, PPCC",
    "Sikkim Pollution Control Board NOC, SPCB-Sikkim",
    "Tripura State Pollution Control Committee NOC, TSPCB",
    "Goa State Pollution Control Board NOC, GSPCB",
    "Jammu & Kashmir Pollution Control Committee, JKPCB",
    "Meghalaya State Pollution Control Committee, MSPCB",
    "Andhra Pradesh Pollution Board NOC, APPCB",
    "One Person Company",
    "Limited Liability Partnership Registration",
    "Private Limited Company",
    "FSSAI",
    "DSC or Digital Signature Certificate",
    "IEC code",
    "Microfinance company registration",
    "NBFC registration",
    "Asset reconstruction company registration",
    "Mutual fund company registration",
    "BIS Certification",
    "Foreign Manufacturer Certification Scheme",
    "Indian Standards Institute Certification",
    "Compulsory Registration Scheme",
    "AYUSH Manufacturing License or AYUSH License",
    "TEC certificate",
    "WPC certification",
    "BEE certification",
    "AERB approval or AERB license",
    "EPR certificate",
    "Automotive Research Association of India certification",
    "ISO Certification",
    "FCC Certificate",
    "Federal Communications Commission",
    "NRTL Approval",
    "Nationally Recognized Testing Laboratory",
    "China CCC certification service",
    "CCC certificate",
    "CCC automotive certification",
    "china CCC automotive certification",
    "China SRRC Certification",
    "SRRC certificate",
    "China NAL Certification",
    "NAL certificate",
    "China CCIS Certification",
    "CCIS certificate",
    "China MIIT Network approval license",
    "MIIT approval",
    "Ministry of Information and Information Technology Approval",
    "China CMIIT Radio Type Approval",
    "China Ministry of Industry and Information Technology approval",
    "China CEL Certification",
    "CEL Certificate",
    "NOM Certification",
    "NOM certificate",
    "IFETEL Certification",
    "IFETEL Certificate",
    "Japan PSE Mark Certification",
    "PSE Certificate",
    "Japan TELEC Certification service",
    "TELEC Certificate",
    "Japan VCCI Certification Service",
    "VCCI Certificate",
    "Japan Telecom Certification",
    "South Korean KC Certification",
    "KC certificate",
    "Taiwan BSMI Certification",
    "BSMI certificate",
    "NCC Type Approval",
    "National Communications Commission approval",
    "Regulatory Compliance Mark",
    "RCM Approval",
    "Minimum Energy Performance Standards",
    "MEPS Approval",
    "Hygienic certification",
    "Telecommunications Approval",
    "EAC approval",
    "FSB notifications",
    "GOST-R certification",
    "Radio import",
    "ICASA Telecom Equipment Type Approval",
    "Independent Communication Authority of South Africa approval",
    "NRCS certification",
    "National Regulator for Compulsory Specifications certification",
    "SABS certification",
    "South African Bureau of Standards certification",
    "KEBS certification",
    "NRTA certification",
    "National Telecommunication Regulatory Authority certification",
    "CoC certificate, Certificat de controle de qualite certification",
    "Korea Conformity Assessment System for Broadcasting and Communications Equipment certification",
    "CE certification, Conformite Europeenne certification",
    "UKCA mark",
    "UK Conformity Assessed mark",
    "IEC/EN 62368-1 implementation",
    "ANATEL Type Approval",
    "Agencia Nacional de Telecomunicaciones type approval",
    "INMETRO certification",
    "Institute of Metrology",
    "Standardisation and Industrial Quality certification",
    "ENACOM approval, Ente Nacional de Comunicaciones approval",
    "IRAM certification",
    "Instituto Argentino de Normalizacion y Certificacion",
    "Industry Canada (IC) Certification",
  ];

  @override
  List<Widget> buildActions(BuildContext context) {
    return [
      IconButton(
        icon: Icon(Icons.clear),
        onPressed: () {
          query = "";
        },
      ),
    ];
  }

  @override
  Widget buildLeading(BuildContext context) {
    return IconButton(
        onPressed: () {
          close(context, null);
        },
        icon: Icon(Icons.arrow_back_outlined));
  }

  @override
  Widget buildResults(BuildContext context) {
    return Container();
  }

  @override
  Widget buildSuggestions(BuildContext context) {
    List<String> matchQuery = [];
    for (var fruit in searchTerms) {
      if (fruit.toLowerCase().contains(query.toLowerCase())) {
        matchQuery.add(fruit);
      }
    }
    return ListView.builder(
      itemCount: matchQuery.length,
      itemBuilder: (BuildContext context, index) {
        return ListTile(
          title: Text(matchQuery[index].toString()),
          onTap: () {
            print(matchQuery[index]);
          },
        );
      },
    );
  }
}
